### ISSUE TITLE
Добавить документацию по новым компонентам

### ISSUE THREAD

**Issue by novkri** [egal/widget-library#164]
- [ ] Дописать в EPagination описание события `update:modelValue`
- [ ] Дописать документацию по обновлениям в ENavbar (#157)
- [ ] Добавить документацию по ESnackbar (#156 )
- [ ] Добавить документацию по EBurger (#158)
- [ ] Добавить документацию по ENotification (#159)
- [ ] Добавить документацию по анимированным компонентам (#160 )
- [ ] Добавить документацию по ETable (#163)

**Comment by novkri** [comment]
Готово, нужно замерджить ветку с доками
